security:
    # Gestion des encodages de mot de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Fournisseurs d'utilisateurs : on utilise l'entité User pour charger les utilisateurs depuis la base de données
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            # Point d'entrée : utiliser form_login pour rediriger vers /login
            entry_point: form_login

            # Le formulaire de connexion
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            
            logout:
                path: app_logout
                # Redirection après la déconnexion (ici vers la page de login)
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
                # Le "Remember me" est activé par une case à cocher dans le formulaire
                # Décommente la ligne ci-dessous si tu veux l'activer automatiquement
                # always_remember_me: true

    # Contrôle d'accès basé sur les rôles des utilisateurs
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # Exemple d'accès restreint à l'admin
        - { path: ^/profile, roles: ROLE_USER }  # Exemple d'accès restreint aux utilisateurs connectés

when@test:
    security:
        password_hashers:
            # Utilisation de hashers plus légers pour les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # Valeur minimale pour bcrypt
                time_cost: 3  # Valeur minimale pour argon
                memory_cost: 10  # Valeur minimale pour argon