controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Route pour la page d'accueil
app_home:
    path: /
    controller: App\Controller\HomeController::index

reset_password_request:
    path: /forgot-password
    controller: App\Controller\ResetPasswordController::request

student:
    path: /student
    controller: App\Controller\StudentController::index

app_logout:
    path: /logout